### ISSUE TITLE
App closes immediately

### ISSUE THREAD

**Issue by OsmoticAbsorption** [brandonp2412/Flexify#104]
**Describe the bug**
App immediately closes upon opening

**To Reproduce**
1. Tap app icon to open
2. App attempts to open
3. App closes immediately before anything loads

**Expected behavior**
App opens, get brought to main page 

**Screenshots**
![App attempting to open](https://github.com/user-attachments/assets/e89b8a70-64bd-4216-8a24-e2e79c7e1025)

![Error Log](https://github.com/user-attachments/assets/818778c3-8206-4700-876c-ef256859b32a)

**Smartphone**
 - Device: Pixel 8 Pro
 - OS: GrapheneOS (Android 14, Build 2024080500)
 - Version: Flexify 1.1.65

**Comment by dqnne** [comment]
This has already been resolved in later versions. Try to update the app

**Comment by OsmoticAbsorption** [comment]
What would the newest version be? F-Droid shows 1.1.65 as the newest

**Comment by dqnne** [comment]
F-droid is notoriously slow with updates. Newest version is 1.1.78, you can install updates using the releases page https://github.com/brandonp2412/Flexify/releases/tag/1.1.78

https://github.com/brandonp2412/Flexify/issues/95#issuecomment-2257344357

**Comment by OsmoticAbsorption** [comment]
That worked. Allowed me to update the app which allowed me to open the app. Can start tracking my gains again.

Thank you!
