### ISSUE TITLE
Add i18n (translations)

### ISSUE THREAD

**Issue by danilolutz** [brandonp2412/Flexify#107]
**Is your feature request related to a problem? Please describe.**

Nope, It os not related with a problem.

**Describe the solution you'd like**

Translations in other languages

**Describe alternatives you've considered**

**Additional context**

**Comment by brandonp2412** [comment]
I won't be adding this because I wouldn't enjoy working on the project if it had translations. It makes searching for code and editing code tiresome for me. Sorry.

**Comment by danilolutz** [comment]
Hello, nice! The problem isn't the interface but exercises names, but with name editing this will be solved, thanks man!
