### ISSUE TITLE
UX: Add counter for warmup sets shown during plan execution.

### ISSUE THREAD

**Issue by lckr** [brandonp2412/Flexify#109]
Hi @brandonp2412,
Thanks for all the work already put into this nice app.

**Describe the solution you'd like**
Currently, the UI shown during a running workout only displays a counter for working sets as bars below the exercise name, e.g. see example from the README.md 
![here](https://github.com/brandonp2412/Flexify/blob/34550f2dd3098f5c25a49250e29dba5a43f98e82/fastlane/metadata/android/en-US/images/phoneScreenshots/4_en-US.png).
I'd like also to have an option to display warm-up sets in a similar manner.

**Describe alternatives you've considered**
My current workaround is to create a copy of the exercise, e.g. for "Pullup" I would create a "Pullup - Warm-Up" exercise, which I schedule before the actual working set of the exercises. 
This is a lot of manual work and also adds progress tracking of of the warm-up exercise variant in which I'm not really interested.
Besides that we can already specify the number of warm-up sets when we add an exercise to a workout plan and only lack a visual representation in the UI

I can try to add this as a contribution if this would be welcome :)

**Comment by brandonp2412** [comment]
Long tap an exercise item then go into settings to set warmup sets. If your app doesn't have this it's out of date

**Comment by dqnne** [comment]
@brandonp2412 I believe what @lckr meant was to add an indicator/counter for warm-up sets, like the progress bars for working sets. Right now warm-up sets is just a number you set but it doesn't actually do anything when it comes to counting sets AFAIK.

Personally I'm not interested in counting warm-up sets overall but I can see why this could be a nice option to add for those who are, as long as it doesn't make the UI too confusing

**Comment by lckr** [comment]
Yeas, @dqnne is right. It would be nice to have an indicator which tracks the number of warm-up sets similar to the indicator for the number of working sets.
Btw, are the warm-up sets I can configure in an exercise item's setting used for anything at the moment?
