### ISSUE TITLE
Create custom exercises, and add plans not tied to a day with a custom name

### ISSUE THREAD

**Issue by jp-lesage** [brandonp2412/Flexify#11]
Hi!

I've been using Massive for a while and tried to move to Flexify, but in its current state, it is practically useless for me. It looks great and works great, but it is missing some important features from Massive.

My two main issues are the following:
- The list of exercises is static, and out of it, only two are part of my plans. I cannot document the other exercises unless I do some mental gymnastics and maintain a mapping to entries from the static list outside of the app, which is counter-productive.
- Plans are tied to a day and cannot have a custom name. I train every other day, and I have 3 plans. They never fall on the same days. I also want to keep my older plans and be able to name them accordingly.

The static list of exercises is a show-stopper for me and probably a lot of other potential users. The issue with the plans I can live with (for now), but will be exacerbated if you have more than 7 plans that you rotate through (or just want to keep your plans for archiving purposes). Having 3 plans named "Monday" and having to check the exercises to see which "Monday" you need to document is more complicated than looking up plans by their custom name.

Is it planned to bring these two features into Flexify?

Thanks!

**Comment by brandonp2412** [comment]
Any feature not included across from Massive was one that I didn't personally use. Feature requests like this will help me add the ones which people actually want.

I can add titles to plans and might make the exercise list editable in the future. However having a static list comes with a lot of benefits and the costs are few (semantically different names e.g. bench press or bench presses). I personally went through and edited my existing exercises to match the names of the static list. The biggest thing I wanted was this app to be as fast as possible, and the way I see it exercises in real life are static and very infrequently changed.

**Comment by brandonp2412** [comment]
Why don't you show me the names which aren't included and we can see if they are truly different exercises and make the static list as comprehensive as possible, or figure out if some of these are mere semantic differences

**Comment by jp-lesage** [comment]
Hi!

I understand the reasons for a fixed list, but it also removes a lot of the flexibility that Massive provides.

I'll go through my plans and make a mapping between "plan vs. app" and update the issue once I have the full list. I'll try to find the closest match in the app-provided list, but most of the times the closest match isn't precise enough. I should have some time to do that later today.

Thanks!

**Comment by jp-lesage** [comment]
Awesome!

I downloaded v1.0.25, and it seems to work great!

However, the app displays the number keyboard with no possibility to switch it when trying to type a new name... Editing it after creation does show the correct keyboard and allows to set the correct name.
![Screenshot_20240325_075718.png](https://github.com/brandonp2412/Flexify/assets/53324016/04bbae5f-e017-417b-8598-da91890ac970)

The creation date also stays null (but it might be intended):
![SmartSelect_20240325_080435_1.png](https://github.com/brandonp2412/Flexify/assets/53324016/c581fc3f-8b11-4fb0-9337-f1e55e3747f9)

Thanks!

**Comment by brandonp2412** [comment]
Fixed number keyboard bug and I saw that was a bug elsewhere as well so included it in the commit

**Comment by jp-lesage** [comment]
Hi! I can confirm the keyboard issue is not present anymore in v1.0.26. Thanks!
