### ISSUE TITLE
Allow modification of exercise name

### ISSUE THREAD

**Issue by lckr** [brandonp2412/Flexify#110]
**Describe the solution you'd like**
Currently, it is not possible to modify the name of an exercise once it is created within the app. 
My motivation is the following: Assume for an example that I perform an exercise named "A" which I'm tracking for multiple weeks. Now I decide to include a new variant of "A" in my next cycle which I'll call "A.2" and would like to rename "A" to "A.1" in order to avoid confusion (here "A" could be "Leg Curls", "A.1" and "A.2" could be "Seated Leg Curls" and "Lying Leg Curls", respectively).

**Describe alternatives you've considered**
One alternative would be to just create a new exercise "A.2" and use this exercise from now on instead of "A" and optionally delete "A". This would not transfer the historical statistics of "A" to "A.2". (Also I didn't find the option to delete an exercise in the app yet).

**Comment by dqnne** [comment]
You can modify the name of exercises and delete them. Go to the Graphs page, long press on an exercise to select it, and press the trash icon in the top right to delete it, or press the three dots and go to Edit to change the name.

**Comment by lckr** [comment]
Ah, that's great. Thank you. The UI/UX partially feels a bit non-intuitive for a new user, are you open to some suggestions?

**Comment by dqnne** [comment]
Sure, suggestions are always good. I'm just a contributor though so I don't choose what gets implemented. If you have specific changes in mind you can open issues for them
