### ISSUE TITLE
Rep amounts change when switching apps

### ISSUE THREAD

**Issue by johnpbloch** [brandonp2412/Flexify#118]
First, thanks for all the work you put into this app! I've found it very simple and helpful for tracking my workouts.

**Describe the bug**
If I switch to another app (it seems to be any app at all, but I haven't tried every app on my phone) in the middle of a workout, when I come back to Flexify, the rep count of the current exercise will have changed to some other number than it had been. I have not been able to find any pattern behind what the number is.

**To Reproduce**
1. Go into a saved workout and add a set from the list.
2. Switch to a different app for a bit.
3. Switch back to Flexify.
4. Rep count is different.

**Expected behavior**
When switching back to Flexify from another app, the rep count should not have changed

**Smartphone:**
 - Device: OnePlus 6T
 - OS: LineageOS 21-20240820-NIGHTLY-fajita
 - Browser: Firefox 129.0
 - Version: 1.1.85

**Comment by brandonp2412** [comment]
That's a feature go into settings and disable rep estimation. It was supposed to be off by default so I'll keep this ticket open

**Comment by johnpbloch** [comment]
:sweat_smile: whoops, didn't realize what that setting meant haha. Thanks for helping me out!
