### ISSUE TITLE
Adding a new exercise when creating a plan deselects all selected existing exercises

### ISSUE THREAD

**Issue by philipwilk** [brandonp2412/Flexify#122]
**Describe the bug**
If you press the + button in the search bar to create a new exercise while creating a new plan, all currently selected exercises get deselected.

**To Reproduce**
1. Create a new plan
2. Select one or more exercises
3. Create a new exercise from the search bar button
4. All exercises have been deselected from the plan you are creating

**Expected behavior**
Selected exercises should stay selected after creating a new exercise.

**Smartphone (please complete the following information):**
 - Device: Redmi note 13 pro 5g
 - OS: hyperos 1.0.16.0/android 14
 - Version 1.1.86

**Comment by brandonp2412** [comment]
Check if https://github.com/brandonp2412/Flexify/releases/tag/1.1.88 or 1.1.87 fixes it

**Comment by philipwilk** [comment]
still happens on 1.1.88
also neither 87 or 88 are on fdroid btw
