### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [brandonp2412/Flexify#16]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6674687227 The version code of your apk is 581, could you please check that? Thanks!

**Comment by brandonp2412** [comment]
OK I think this was my `deploy.sh` script sending the release at the wrong time to github.

How do I subscribe to something in the f-droid gitlab pipelines to get a notification if it succeeds/fails next time around? Trying to set up fdroid server to run these builds on my pc locally and test but having a hard time doing it

**Comment by linsui** [comment]
> How do I subscribe to something in the f-droid gitlab pipelines to get a notification if it succeeds/fails next time around?

I don't know...

> Trying to set up fdroid server to run these builds on my pc locally and test but having a hard time doing it

You can use the docker image directly.

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6713551707

**Comment by licaon-kter** [comment]
@brandonp2412 here's the diff: [flex701.log.zip](https://github.com/brandonp2412/Flexify/files/15111953/flex701.log.zip)

**Comment by linsui** [comment]
1.1.71 failed. 
[flexify-x86_64-release.apk.html.zip](https://github.com/user-attachments/files/16373486/flexify-x86_64-release.apk.html.zip)

**Comment by licaon-kter** [comment]
reopen, https://monitor.f-droid.org/builds/log/com.presley.flexify/1961#site-footer

were the APKs in https://github.com/brandonp2412/Flexify/releases/tag/1.1.87 built from https://github.com/brandonp2412/Flexify/commit/23affbd78ad6cc6eb4213f76903e5a1caaa27b6d ? So many differences...

**Comment by licaon-kter** [comment]
can we reopen? https://gitlab.com/fdroid/fdroiddata/-/jobs/8097605935#L1581

maybe you can try to clean up cache @brandonp2412 and rebuild from https://github.com/brandonp2412/Flexify/commit/0c1e714ddd20da2e5fde0661946081dbabf10a70 ? don't replace the APK just attach  app-arm64-v8a-release.apk  here renamed as ZIP (don't archive!) so we can test

**Comment by brandonp2412** [comment]
@licaon-kter what cache am i cleaning? gradle cache?

**Comment by linsui** [comment]
Yes, the gradle build cache. :)

**Comment by brandonp2412** [comment]
@linsui not sure if that works but github just says uploading forever, ill check again later

**Comment by licaon-kter** [comment]
Retry :)

**Comment by linsui** [comment]
Fixed, thanks!
