### ISSUE TITLE
Graph line goes above the graph and over other controls when "Curve line graph" is enabled

### ISSUE THREAD

**Issue by jp-lesage** [brandonp2412/Flexify#20]
Hi!

As the title says, the graph curves shoot outside of the graph and into the top section of the UI when the `Curve line graph` setting is enabled.

I'm not sure if the library used to render the graph supports it, but the lines should plateau a bit more aggressively instead of shooting up and then going back down.

Screenshot from v1.0.59 of how it looks like, along with a proposed line of how it could be (in red-ish):
![Screenshot_20240422_072816.png](https://github.com/brandonp2412/Flexify/assets/53324016/d04ab8f1-63aa-4585-a7b4-b38d31b7caf1)

My graph drawing skills are not on point, but the line should be contained within the graph itself. Making the graph slightly bigger can prevent the line from over-shooting the graph boundary, however, as it is, it may not represent the actual progress based on the entered data (in this case, I never used anything other than a 30lbs barbell, and the graph going higher than that doesn't make much sense).

One thing I didn't test is how it looks with multiple data points (I only have two...). With higher values (Volume graph, for example), it does the same, but the line doesn't go that high outside the graph borders.

Thanks!

**Comment by brandonp2412** [comment]
Yeah this is an issue I knew about and its why I chose to have non curved by default. I don't see myself working on that library so there isn't much for me to do with this issue. I suggest disabling the curves if the visual bug is too annoying

**Comment by jp-lesage** [comment]
That's what I figured, and that's fair enough. As I mentioned, the higher the values the less pronounced the "bump" is, and it's only a minor cosmetic thing.

Thanks!
