### ISSUE TITLE
Set data does not save when rest timers are enabled

### ISSUE THREAD

**Issue by Dermanthi** [brandonp2412/Flexify#22]
Hey,

I seem to be having the opposite problem to Issue #17.

When rest timers are enabled, the rest timer activates, however the set data does not seem to save. Disabling the rest timer allows the sets to save as expected.

Cheers

**Comment by brandonp2412** [comment]
This is why I shouldn't be doing updates with a wrist injury. Embarrassing.

**Comment by brandonp2412** [comment]
Honestly I need better tests

**Comment by Dermanthi** [comment]
You're all good, these things happen.

I'm liking the project so far, keep up the good work.

**Comment by tomas-samot** [comment]
I still have this issue on the latest version from F-droid.

**Comment by brandonp2412** [comment]
It's fixed in 1.0.61 onward. F-droid will take longer to get recent updates than the Play store + github releases.

**Comment by tomas-samot** [comment]
I got the update from GitHub instead of play store.
