### ISSUE TITLE
Massive's db or sets import 

### ISSUE THREAD

**Issue by hirako2000** [brandonp2412/Flexify#23]
As [Massive](https://github.com/brandonp2412/Massive) is being phased out, it would be awesome if we could expect to be able to export its db and import it into Flexify.

It's also probably easier to get on with it to support the import of more and more fields as dev goes along than adding support for all imports when the new app becomes full fledged.

If db migration to the new app is too much of a headache, being able to import `sets` from legacy (Massive) CSV exports would be enough. 

Thanks so much for these apps, and for open sourcing it. The philosophy is great, graphs look super promising, timer is awesome and done right, UI overall is sleek and minimalist which is ideal for a workout log app really.

**Comment by brandonp2412** [comment]
CSV import/export are already supported. Migration is outlined on the README. Its in the settings page.

**Comment by hirako2000** [comment]
My apologies, I tried to import and I had to edit entries. But I didn't follow the migration steps. Thanks.

**Comment by Dermanthi** [comment]
@brandonp2412 
> CSV import/export are already supported. Migration is outlined on the README. Its in the settings page.

As of now, it seems that one would have to modify the sets.csv file from massive for it to import successfully (plans.csv does import correctly). You'd need to remove the quotations and add one decimal place to each entry's number.

For example:

```
"id","name","reps","weight","created","unit","hidden","image","sets","minutes","seconds","steps"
"1","Test","0","0","2024-04-24T14:39:39",,"0",,"3","3","30",
```

Would need to be modified to:

```
"id","name","reps","weight","created","unit","hidden","image","sets","minutes","seconds","steps"
"1","Test",0.0,0.0,"2024-04-24T14:39:39",,0.0,,3.0,3.0,30.0,
```

I had this issue when doing my own migration earlier.

**Comment by tomas-samot** [comment]
I have now upgraded to latest version and I am trying to import sets from the Massive. The above instructions are not working and trying to import the unedited CSV doesn't work either. I just get records with numbers in it.

**Comment by brandonp2412** [comment]
Please provide a minimal reproducible sample (paste the CSV here) and list the app version this occurs on

**Comment by Dermanthi** [comment]
> I have now upgraded to latest version and I am trying to import sets from the Massive. The above instructions are not working and trying to import the unedited CSV doesn't work either. I just get records with numbers in it.

Could you try removing the quotations from the ID if they are present.

For example:
```
"id","name","reps","weight","created","unit","hidden","image","sets","minutes","seconds","steps" 
1,"Test",0.0,0.0,"2024-04-24T14:39:39",,0.0,,3.0,3.0,30.0,
```

I just did another test with the latest patch and that seemed to fix an import issue for me.

**Comment by brandonp2412** [comment]
> > I have now upgraded to latest version and I am trying to import sets from the Massive. The above instructions are not working and trying to import the unedited CSV doesn't work either. I just get records with numbers in it.
> 
> Could you try removing the quotations from the ID if they are present.
> 
> For example:
> 
> ```
> "id","name","reps","weight","created","unit","hidden","image","sets","minutes","seconds","steps" 
> 1,"Test",0.0,0.0,"2024-04-24T14:39:39",,0.0,,3.0,3.0,30.0,
> ```
> 
> I just did another test with the latest patch and that seemed to fix an import issue for me.

This sample csv worked for 1.0.69. What version are you using?

**Comment by tomas-samot** [comment]
I am currently running `1.0.69`.

This is my edited sets CSV:
```
"id","name","reps","weight","created","unit","hidden","image","sets","minutes","seconds","steps"
10,"Seated Row",5.00,50.00,"2024-01-08T18:30:30.000Z",,0.00,,3.00,3.00,30.00,
11,"Seated Row",5.00,45.00,"2024-01-08T18:30:17.000Z",,0.00,,3.00,3.00,30.00,
```
I import this into plans. Nothing gets imported.

This is the original file:
```
"id","name","reps","weight","created","unit","hidden","image","sets","minutes","seconds","steps"
"10","Seated Row","5","50","2024-01-08T18:30:30.000Z","kg","0","","3","3","30",
"11","Seated Row","5","45","2024-01-08T18:30:17.000Z","kg","0","","3","3","30",
```

I've tried to import my sets into plans and graphs. Which one should I use?
I also don't use plans. I just track what every movement I can do that session.

**Comment by brandonp2412** [comment]
> I also don't use plans. I just track what every movement I can do that session.

This app doesn't have a free-form input for sets so this style of working out is probably not best for Flexify.

**Comment by hirako2000** [comment]
> > I also don't use plans. I just track what every movement I can do that session.
> 
> This app doesn't have a free-form input for sets so this style of working out is probably not best for Flexify.

Checking the README , was led to believe the countary:

> Track Gym Progress: Flexify allows you to effortlessly track your gym progress. Log your workouts, sets, reps, and weights with ease

I assumed Flexify would allow the tracking of specific sets and reps and weights as Massive does.

As a user I would really value being able to do what Massive was capable of doing very well: the tracking of individual workouts off plan templates. Where I can add the entity of a workout off a template represented by sets, number of reps and weight for each. And that when adding the tracking of a set it auto complete reps and weight from the latest tracking. It is magically convenient and powerful in Massive.

As a user, I don't care much what time my workout took place in the graphs, what matter most to me is evolution over weeks, months, years. I want to visualize how many reps and weight I performed, how long workouts last, frequency of workouts, over time. 

Sorry to dump a set of desire in this thread but I thought it was adequate as the issue is concerning users migrating or hoping to want to migrate from Massive, eventually.

Of course I'm biased and train a particular way, maybe I do not understand how Flexify approach to tracking with just 'Plan' effectively is more hopeful. And of course this is your project and you should take the directions you believe is the best.

**Comment by brandonp2412** [comment]
Free form adding of sets is something I could easily add but this issue is about importing things via CSV. Make a separate issue if that's a feature you want

**Comment by tomas-samot** [comment]
> > I also don't use plans. I just track what every movement I can do that session.
> 
> This app doesn't have a free-form input for sets so this style of working out is probably not best for Flexify.

I appreciate that. I was going to try and use plans and if it wasn't viable for me, switch back to massive.

Am I doing this all wrong then? I cannot just import all my sets from Massive into Flexify? Do the sets need to be associated to a plan?

**Comment by Dermanthi** [comment]
@tomas-samot 

> Am I doing this all wrong then? I cannot just import all my sets from Massive into Flexify? Do the sets need to be associated to a plan?

> Also am I importing my sets.csv into the correct data import type? Should it go into plans or graphs?

I managed to test importing on an empty session and both examples you've given work. They need to be imported as "Graphs"

They don't seem to require a plan associated to import the history. However you will not be able to add new sets until you create a plan afterward.

**Comment by tomas-samot** [comment]
@Dermanthi 
When I try to import the full edited `sets.csv` into graphs I get this error:
```
RangeError (index): Invalid value: Only valid value is 0: 1

```

**Comment by Dermanthi** [comment]
Are you testing using the sample you provided, or a much larger file?

**Comment by tomas-samot** [comment]
I'm using the full file. which has 981 lines. Damn, the small file does import. I just tried it now. Is that too many lines?

**Comment by Dermanthi** [comment]
My own file had 1080 lines, and that imported fine, so I doubt that would be the issue. 

There's got to be something, somewhere in the csv that just won't work. Perhaps if you attach the full file, I could take a look.

**Comment by tomas-samot** [comment]
I found out what the problem is. I was editing the file on a Windows machine and the CSV file was saved with Windows-1252 encoding. I've edit now on my Linux machine with UTF-8 encoding. Imported the whole 981 lines files without issue. Expect maybe a pectoral fly came in at 119.05kg when the max I've done is 110kg (on a machine).

**Comment by Dermanthi** [comment]
> Expect maybe a pectoral fly came in at 119.05kg when the max I've done is 110kg (on a machine).

I'd suggest now clearing the Flexify history and importing a freshly made csv generated from Massive without editing it at all. See if that works. Just make sure you're using the latest version.

Although do take note that Massive has this issue where if `sets.csv` is already present it creates `sets.csv (1)` instead of `sets (1).csv`, which just means you might have to fix the file extension.

**Comment by brandonp2412** [comment]
Must be the windows vs Linux encoding I've got to make a windows encoded file and figure out the fix for importing it

**Comment by tomas-samot** [comment]
> Must be the windows vs Linux encoding I've got to make a windows encoded file and figure out the fix for importing it

Not necessarily if you want people to just import from Massive directly. I suppose docs and a check to say the file is not UTF-8 encoded please resave in UTF-8 would be enough?

**Comment by tomas-samot** [comment]
> > Expect maybe a pectoral fly came in at 119.05kg when the max I've done is 110kg (on a machine).
> 
> I'd suggest now clearing the Flexify history and importing a freshly made csv generated from Massive without editing it at all. See if that works. Just make sure you're using the latest version.
> 
> Although do take note that Massive has this issue where if `sets.csv` is already present it creates `sets.csv (1)` instead of `sets (1).csv`, which just means you might have to fix the file extension.

This process works now on version `1.0.69`. Nice, thank you everyone for helping.

@brandonp2412 Thank you for Massive and Flexify.

**Comment by brandonp2412** [comment]
Really struggling to replicate this bug but I have seen it before in the past. Here's what I tried:

1. Created this file and specified windows encoding + CRLF
![image](https://github.com/brandonp2412/Flexify/assets/14083541/422af764-80f6-47b9-8d52-1f76d99d439c)
2. Sent it to my emulator `adb push documents/sets.csv /sdcard/Download`
3. Imported it on my emulator successfully

Doing all of this from windows BTW

**Comment by brandonp2412** [comment]
Even if I can't replicate it I can just push a release that tries both \n and \r\n line endings and then you could check if it fixes it?

**Comment by brandonp2412** [comment]
It wasn't the line endings. I managed to make a file that wouldn't read properly. It must be to do with the file encodings like you said. My kotlin code reading the file probably needs to handle parsing different file encodings :cry:

**Comment by brandonp2412** [comment]
I have changed the way file picking works, and this ticket has grown pretty big beyond the scope of what it should be doing. If someone else runs across this issue we can make a more targetet ticket for it.
