### ISSUE TITLE
Add ability to change number of sets

### ISSUE THREAD

**Issue by RageKnify** [brandonp2412/Flexify#27]
Hey, started using the app recently and really liked how simple and clean it is.

One thing that I felt missing is the ability to choose how many sets to do either per exercise or in general for the whole workout.

I like to do 3 sets and the app seems to be intended to be used only with 5 sets in mind.

I understand having it changeable for each exercise in a workout might be a lot of work but I would be happy with an app wide setting.

**Comment by brandonp2412** [comment]
Yeah I was thinking the same thing. Also could be easier for the user to have an app-wide setting anyway. I found myself on Massive frequently changing from different max # of sets. E.g. one week you manage to squeeze in new records but the next week you fail to add more weight, so you add more volume instead (increase the # of max sets per exercise).
