### ISSUE TITLE
Add ability to see all reps of last workout

### ISSUE THREAD

**Issue by RageKnify** [brandonp2412/Flexify#28]
I've been missing the ability to see how many reps I did in all sets of the previous workout.
Sometimes I will do 8-8-8-8-9 and when I get back to the exercise I don't remember and I'll only know I did 9 in the last set.

By having full visibility I'll know to target 8-8-8-9-9 next time.

Do you think this is something you could incorporate?

**Comment by brandonp2412** [comment]
History can be seen after viewing a graph by tapping the bottom right button https://github.com/brandonp2412/Flexify/blob/main/fastlane/metadata/android/en-US/images/phoneScreenshots/6_en-US.png

**Comment by brandonp2412** [comment]
If this ticket is asking for that info to be in-line on the plans page I won't be adding this. The screen real-estate is almost completely spent in most plans.

**Comment by RageKnify** [comment]
I would say that the exercise list being scrollable makes it ok to have more info.
But I would be okay with putting this info anywhere that I could access.
Just to make sure it's doable, the app does store the weight and reps for each set that is done, right?

**Comment by timonsky** [comment]
has this ability to view the history been removed intentionally? I guess at the time of posting the screenshot was actually this https://github.com/brandonp2412/Flexify/blob/b435e86d28719569f84268259af6417f7317d2da/fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png, not the one the link leads to now where it doesn't show the bottom right button
