### ISSUE TITLE
How to do all the workouts ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [brandonp2412/Flexify#33]
First of all: Great, an app that already has many workouts included.

But i don't know how to do all the workouts.

Maybe there will be an explanation in later releases, who knows.

**Comment by brandonp2412** [comment]
In the plans page tap one of the plans (probably today's one). Then enter your reps/weight for a set. Tap save. Continue this for each exercise until you are done.

**Comment by mondlicht-und-sterne** [comment]
> In the plans page tap one of the plans (probably today's one). Then enter your reps/weight for a set. Tap save. Continue this for each exercise until you are done.

You have now explained how I should practise this.
But how am I supposed to know how all these exercises are practised?
It's not written anywhere.
That's what I meant.

**Comment by brandonp2412** [comment]
I won't be putting in Flexify tutorials of how to do exercises
