### ISSUE TITLE
Graphs to properly represent history logs

### ISSUE THREAD

**Issue by hirako2000** [brandonp2412/Flexify#34]
### steps to reproduce 

Track some history entries, in my case I've tracked 3 different named entries. Single day work out. And one named entry, the day before.

### expected graph

- I would expect the dot to be higher on the axis. The issue might be due to the fact there is no range to establish where to put that dot with just a few entries, I don't know. Somewhere above the middle would make sense to me. Anywhere but at y zero. 

- the one named entry also got the issue. I would expect a line/curve to form since I tracked entries for that one two days in a row.

### actual

![Screenshot_20240508_233411](https://github.com/brandonp2412/Flexify/assets/1500712/19a97cf9-730f-4cde-8297-32e3a44da048)
![Screenshot_20240508_233432](https://github.com/brandonp2412/Flexify/assets/1500712/0ff3e57d-496d-410d-a660-5ff027f2d514)

**Note** those entries were imported via CSV, not typed in via Flexify. But they look like totally correct history logs in the history tab with weight , about of reps, date.

**Comment by brandonp2412** [comment]
Yeah not sure why but there's this bug with the graphs where some days don't register as being on separate days. It happens I think when the time difference between them isn't large enough? I have tried many things and still think about this bug every now and then.

**Comment by hirako2000** [comment]
I see a compounding of issues in there.

From what I'm seeing one issue is when the values are all identical. They have nothing to scale and bottom to y = 0 for all points.

With the example above, all weights are the same.

I've reproduced it with a fresh set.

### steps to reproduce

Having nothing in the history tab

- Create 3 gym set logs, each with about a day or more apart as date.
- have all 3 entries all have the same weight and number of reps
- go to graphs tab and select that gym set.

### expected

- graph with lines or curved across 3 points somewhere above the x axis.

### actual

- graph shows a straight line over the x axi

![Screenshot_20240509_060227](https://github.com/brandonp2412/Flexify/assets/1500712/838213e7-451c-4ea6-8585-205ba43b9390)


That's maybe problem with determining the right scale and/or determining an appropriate min and max given a certain range ? Perhaps adopting d3 utilities, or even d3 even for rendering, you will have a much easier time with difficult to come up with appropriate logic to plot data meaningfully in all possible crazy scenarios users come up with. (d3 range article)[https://observablehq.com/@d3/d3-range]

Another issue is the single dot. It happens when the datetime in between two entries is short. Here with just 2 history entiers 24h apart:

![Screenshot_20240509_060903](https://github.com/brandonp2412/Flexify/assets/1500712/f18e8112-a961-42b3-83af-58248e95587c)

Cases where weights differ, and with at least 3 entries seem to work fine even though the time between each entry is as as small:

![Screenshot_20240509_060113](https://github.com/brandonp2412/Flexify/assets/1500712/d04dc38d-0c92-4397-8d9c-6abdfc739df6)
![Screenshot_20240509_060149](https://github.com/brandonp2412/Flexify/assets/1500712/90009747-30de-4b11-90cf-438819ef7b96)

**Comment by brandonp2412** [comment]
I initially wrote a bunch of logic for scaling the Y axis, but it sacrificed a lot of features the chart author has put into his implementation. In the end it added an equal number of visual quirks (maybe more) than it fixed.

I'm going to close this ticket since it mainly contains suggestions I'm not going to make, however feel free to make a separate one for the bug where different day entries appear as a single dot.
