### ISSUE TITLE
Add exercise override setting for sets and rest length

### ISSUE THREAD

**Issue by josephnglynn** [brandonp2412/Flexify#37]
Related to #27 I think.

At the moment all exercises inherit the global rest duration and set amount.

Most exercises I do follow the same duration and sets, but there's a few where I prefer to do more sets / have more rest between sets.

Would it be possible to add a toggleable override for specific exercises which differ from the global setting in those aspects?

**Comment by brandonp2412** [comment]
Anything for the King.

**Comment by RageKnify** [comment]
Hey @brandonp2412 I'm probably just not looking in the right place, but I can't find where to change the number of sets and the length of the timer.
Could you please remind me where to look?

**Comment by brandonp2412** [comment]
@RageKnify it's in the graph edit page
