### ISSUE TITLE
Problem with history

### ISSUE THREAD

**Issue by akrram0** [brandonp2412/Flexify#40]
So when I'm in the middle of working out iuse the plans page to save my reps and weight for any exercises so for example after ido one set so the exercise is shown in the history page when I try to add my weight and reps for the second set on that page it doesn't count it up like I didn't add it

**Comment by brandonp2412** [comment]
Yep this was a woopsie. I totally broke saving any data.

**Comment by brandonp2412** [comment]
Fixed in 1.0.79

**Comment by akrram0** [comment]
> Fixed in 1.0.79

Heyy thank you for fixing the stop button that was fast but I'm on version 1.0.81 and I tested the history problem but it still has it I included a video and can you add back the number on what set are you in because sometimes I forget🙂 inhttps://github.com/brandonp2412/Flexify/assets/140515513/ff0cae6e-987a-4639-8266-f41140dcbbb7

**Comment by akrram0** [comment]
> Fixed in 1.0.79

Heyy thank you for fixing the stop button that was fast but I'm on version 1.0.81 and I tested the history problem but it still has it I included a video and can you add back the number on what set are you in because sometimes I forget🙂👍 https://github.com/brandonp2412/Flexify/assets/140515513/9b1d9265-d756-48c8-b3ad-bef1a422f727

**Comment by akrram0** [comment]
> Fixed in 1.0.79

Hey thank you but can you bring back the number that tells you what set are you on because a lot of times I forget
