### ISSUE TITLE
Bringing back some old futures

### ISSUE THREAD

**Issue by akrram0** [brandonp2412/Flexify#44]
1. The ability to show which set you're in because I often forget
![IMG_20240524_111538.jpg](https://github.com/brandonp2412/Flexify/assets/140515513/40e952ee-7af7-47a1-841f-3dd79a0dd0b8)

2. Set custom rest time when adding set because I like to rest between each set 1min not 3
 3.  It not old but new impovment, not forcing to make the app always run in the background when setting a timer because I have like low battery capacity (3000meh) and the only time I want the app to work is for one hour is when I working out and not 24/7 I recommend adding a toggle in settings to set it run in the backround

**Comment by brandonp2412** [comment]
1. This is configured by setting the Plan trailing display to "Count"
![Screenshot_1716588576](https://github.com/brandonp2412/Flexify/assets/14083541/82975c00-1191-4789-998b-bacfc79d35be)
2. This is configured when editing a graph
![Screenshot_1716588613](https://github.com/brandonp2412/Flexify/assets/14083541/3cee556f-cefe-4f98-b5d3-a18ce4688920)
3. Timers will not function unless you have background optimizations disabled. This is a "feature" of Android. If you want the app to not worry about optimizations, turn off rest timers
![image](https://github.com/brandonp2412/Flexify/assets/14083541/57d71c9d-4c5c-4d26-822e-ce28b5e3843b)

**Comment by akrram0** [comment]
Hey when I follow the steps of editing time for rest and sets for the exercices (which I didn't know if you didn't told me)I found out it's per exercise, because I've been using the app since long time it would be a big hussle for me even if I wanted to add new exercice same think I have to click more button's it's just not practical, if I want to add more time while resting I just go to timer tab and add 1min while timer is running it would be just as smooth as butter, I recommend to move them to settings and make them general

**Comment by brandonp2412** [comment]
OK ill make:
1. `restMs` per exercise nullable
2. global settings for `restMs` default to 3:30
3. if an exercise has null `restMs` use the global setting
4. otherwise use the setting per exercise

**Comment by akrram0** [comment]
> OK ill make:
> 1. `restMs` per exercise nullable
> 2. global settings for `restMs` default to 3:30
> 3. if an exercise has null `restMs` use the global setting
> 4. otherwise use the setting per exercise

I didn't quite understand 🙂
