### ISSUE TITLE
Error on History tab after update 

### ISSUE THREAD

**Issue by hirako2000** [brandonp2412/Flexify#46]
Updated today. To Version `1.0.92`

Opening the app now displays an error on the history tab. Forced closed the app and restart makes no difference.

![Screenshot_20240528_140216](https://github.com/brandonp2412/Flexify/assets/1500712/771af224-c9ee-4250-8b9d-dda9bffe6536)

**Comment by brandonp2412** [comment]
Could you please post the exported flexify.sqlite?

Or email me it brandon@presley.nz

**Comment by brandonp2412** [comment]
Also which version were you updating from?

**Comment by hirako2000** [comment]
> Also which version were you updating from?

My apology I in fact had not installed the latest just yet. 

Here is the impacted version 

![Screenshot_20240528_155859](https://github.com/brandonp2412/Flexify/assets/1500712/677aaf0a-ea8c-4a70-8126-bc9d7a2ab6f1)
