### ISSUE TITLE
Feature request: Setting for default weight measurement

### ISSUE THREAD

**Issue by TechnologyClassroom** [brandonp2412/Flexify#49]
I track in lbs. It seems as though every time I open a graph, it is in kg. It would be nice to set a default and then only need to change it if something is measured in a different way easier.

**Comment by brandonp2412** [comment]
If you are picking an existing exercise it should use the last ones unit as the default. But we can also have a global default setting.

**Comment by brandonp2412** [comment]
> If you are picking an existing exercise it should use the last ones unit as the default. But we can also have a global default setting.

Woops I wasn't thinking about graphs. Yep we can set this up

**Comment by TechnologyClassroom** [comment]
Wow! Thank you!!!
