### ISSUE TITLE
Play Store Rejecting App

### ISSUE THREAD

**Issue by brandonp2412** [brandonp2412/Flexify#5]
This app keeps being rejected by the play store for the reason of "app unresponsive".
Every version that is rejected for being "unresponsive" is given a screenshot of the app, despite the app working fine on my own devices and emulators. The last rejection said that there was "no content" when tapping the graphs or plans tabs.

**Comment by josephnglynn** [comment]
https://github.com/brandonp2412/Flexify/pull/6 could potentially fix the `app unresponsive` issue, as the UI wasn't updating correcting in certain circumstances.

What page is the app on in the screenshot?

**Comment by brandonp2412** [comment]
They just had a screenshot of the graphs page and said it was "broken" because there isn't any data yet. I have since added a message saying no data yet so hopefully their bots consider that fixed...

**Comment by brandonp2412** [comment]
https://play.google.com/store/apps/details?id=com.presley.flexify
