### ISSUE TITLE
Wrong data types - minor issue

### ISSUE THREAD

**Issue by AmmarHaddadi** [brandonp2412/Flexify#53]
# Problem
As of now, reps can be decimal like 6.7 reps
Reps, weight and body weight can be negative
And these unreal values get interpreted in the graph

# Proposed solution

- [ ] change reps datatype to **int**
- [ ] ensure the minimum value for inputs is 0

> Amazing software bro, I like it

**Comment by brandonp2412** [comment]
Reps can be decimal. Imagine you fail half way through a rep. Weight can also be negative, e.g. assisted pull up machine
