### ISSUE TITLE
Body Weight shown in individual Edit screen for exercises corresponds to current weight

### ISSUE THREAD

**Issue by timonsky** [brandonp2412/Flexify#54]
The (Body) Weight that is shown in the edit screen for individual sets of exercises is not the latest entry for the weight at the time of the set execution, but rather the most recently added body weight entry.

**Comment by brandonp2412** [comment]
This is on purpose. The point of recording your body weight on each set is so you can calculate your relative strength when you completed it.

**Comment by brandonp2412** [comment]
Can you please provide the steps to re-create this bug, and what you expect to see at each point?

**Comment by timonsky** [comment]
My progression of pull ups started with a few sets using an assisted pull up machine, so instead of the weight I actually pulled I inserted the amount of the plates that were subtracted. However that led to negative numbers and in the end screwed with the graphs showing e.g. the relative strength.
So I tried to go back to the individual sets to enter the actual weight [body weight - assistance] I worked with but found that the edit screen showed my current body weight in the field instead of the body weight I had entered when doing the set.

1. enter a body weight via the tree dots in the search bar
2. complete a set
3.  enter a new body weight [e.g. a week later]
4. go to edit screen for set from step 2: body weight shown in field is the one from step 3, not step 1

**Comment by timonsky** [comment]
this is where I encountered the bug

https://github.com/brandonp2412/Flexify/assets/81168204/0fefae22-9b39-432d-8738-c716ef711a5c


but it seems that comes from a problem in the importing from the graph.csv because looking at the db  the body weight is set to 78.2kg on all sets of any exercise

**Comment by brandonp2412** [comment]
Im afraid I don't understand what is the bug here, perhaps you could try explaining this using a minimal example?
