### ISSUE TITLE
ability to see history from single exercise 

### ISSUE THREAD

**Issue by timonsky** [brandonp2412/Flexify#56]
As far as I can see v1.0.69 contained this button on the graph page that allowed to see the history for that single exercise
https://github.com/brandonp2412/Flexify/blob/b435e86d28719569f84268259af6417f7317d2da/fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png

After v1.0.69 the button was removed, and looking at the history for a single exercise now would entail searching for the exercise via the search bar on the history page. Was this functionality removed intentionally?

[ Reappearance of #28 ]

**Comment by brandonp2412** [comment]
Yeah I removed it because I figured nobody would notice since I added the history page, but I can add it back in. Looking at it now i do like how the fab looks with a history icon on it.
