### ISSUE TITLE
Maximum sets not working

### ISSUE THREAD

**Issue by akrram0** [brandonp2412/Flexify#58]
I tried to change the maximum sets but it not working
https://github.com/brandonp2412/Flexify/assets/140515513/1e1b4eda-19aa-4429-ac4f-2c59c8b2a023

**Comment by brandonp2412** [comment]
In your database have you set a custom max sets per exercise as well? That would take precedence over the default in Settings.

You can see it in Graphs -> Exercise -> Edit

**Comment by akrram0** [comment]
> In your database have you set a custom max sets per exercise as well? That would take precedence over the default in Settings.
> 
> You can see it in Graphs -> Exercise -> Edit

No didn't set that, all the exercises, including exercises I never did show 3?

**Comment by brandonp2412** [comment]
Try clearing them in the mean time. I think a migration missed setting all those default values to `null` when I added the custom max sets per exercise.

**Comment by brandonp2412** [comment]
Struggling to replicate this issue on any device (max sets remaining as the default of 3)

**Comment by akrram0** [comment]
> Struggling to replicate this issue on any device (max sets remaining as the default of 3)

hmm yup.. I think the problem is with my database I tried to do the same with a new database and no problem, idk how this happen but is their a way to fix my database?

**Comment by akrram0** [comment]
> > Struggling to replicate this issue on any device (max sets remaining as the default of 3)
> 
> hmm yup.. I think the problem is with my database I tried to do the same with a new database and no problem, idk how this happen but is their a way to fix it?

**Comment by brandonp2412** [comment]
It might be a specific set of versions of the app before I fixed a bunch of migrations issues, I'll try pushing the same migration again where it clears to null all the `maxSets` that equal the global settings one.

**Comment by brandonp2412** [comment]
@akrram0 was your global setting for `maxSets` something other than `3`?

**Comment by akrram0** [comment]
> @akrram0 was your global setting for `maxSets` something other than `3`?

It was 4 before and after you added back the general maximum set I think the problem started when you removed it
