### ISSUE TITLE
Cardio duration

### ISSUE THREAD

**Issue by TechnologyClassroom** [brandonp2412/Flexify#59]
I did not initially realize that Flexify could track cardio. I took photos of all of my stop screens and I will enter them in.

Distance and incline seem good, but duration does not make sense to me. Is duration minutes? It looks like I can enter a decimal value, but I would expect to see HH:MM:SS format or some variation of that. To accurately log time, I would need to divide seconds by 60 to get a decimal if I understand this correctly that duration is minutes.

**Comment by brandonp2412** [comment]
Yeah I didn't put much thought into the cardio feature since i've only recently started doing cardio 😢 

It's stored as a `float` so i'll probably treat it as milliseconds under the hood, and then make visual pickers for minutes/seconds in the relevant places like how we are doing it in Settings.

**Comment by TechnologyClassroom** [comment]
That probably makes sense to keep it as a float. Walking/jogging/climbing would make sense to track in minutes while plank might be seconds. Or the user could be presented with a HH:MM:SS sort of input that is converted to float.
