### ISSUE TITLE
Add ability to set max sets for exercises per-plan

### ISSUE THREAD

**Issue by vemvare** [brandonp2412/Flexify#62]
I think the ability to set max sets for exercises per-plan would be nice. That way you can have multiple plans with the same exercise but with different set count. 

I guess it's already possible to make a copy of an exercise with a different max sets value and use that, but I think an option to pick exercise set count within each plan would be a better experience.

What do you think?

**Comment by brandonp2412** [comment]
The maximum # of sets is starting to get complicated, right now the priority is:

1. Graph edit for maximum sets
2. Settings default for maximum sets
3. Default to 3

If a user only understands 1 or 2 it works fine, they set the # of sets globally and expect it everywhere, or they set it per exercise and expect the rest to be the same. Whats confusing is changing the settings maximum after changing a bunch of graphs. Does it make sense for the most recent setting to take priority? or the most specific?

**Comment by vemvare** [comment]
The most specific setting should generally take precedence in my opinion. 

To me it makes more sense for the exercise-specific set amount to be adjusted on a per-plan level instead of globally in the Graphs page. The only point of changing max sets of an exercise, from my understanding, is to have the set progress bar/count within a plan change to use the new wanted set amount for that exercise. Correct me if I'm wrong.

Users who don't have a workout plan also don't have a use for the current per-exercise max sets setting in the Graphs page. And for users who do have a workout plan, changing the max sets for exercises within the plan would both feel more intuitive and give users freedom to have differing set amounts for the same exercise in multiple workout plans. Personally, the plans page was the first place I looked when I wanted to change the max sets for an exercise in my plan. 

So in my opinion the priority could be this:

1. Per-plan per-exercise setting for maximum sets
2. Settings default for maximum sets
3. Default to 3

Those are just my thoughts. It's probably not an important change, but I think it would be a net positive. It's also more similar to how most of the more popular proprietary workout apps do it.

**Comment by brandonp2412** [comment]
I agree lets do it

**Comment by brandonp2412** [comment]
![image](https://github.com/brandonp2412/Flexify/assets/14083541/1632fe43-e544-47e1-a251-9db49d889911)

how is this looking? I'm going to need to test it a lot before deploying since this changes a lot of core structure

**Comment by vemvare** [comment]
Legend. That looks good and the location makes sense. 

One small detail you could add is to have the current default set amount grayed out inside the input box so it's clear what will happen if you don't explicitly input a number. Maybe some other small tweaks but overall LGTM
