### ISSUE TITLE
App crashes on timer runout

### ISSUE THREAD

**Issue by Dermanthi** [brandonp2412/Flexify#63]
Hey,

Don't quite know where it started, but the last few releases for me have been crashing the app when the rest timer runs out. This leads me to have to navigate the app from the beginning after each set. Currently running latest v1.1.35.

The alarm/notifcation still happens but with reduced information.

![image](https://github.com/brandonp2412/Flexify/assets/143519476/333620fa-8892-4e35-a137-badce6b6975c)

Manually stopping the timer works as normal.

Cheers

**Comment by brandonp2412** [comment]
Try clearing your alarm sound (long press the alarm sound button) or setting it to something else again. If that fixes it then I know what's going wrong

**Comment by Dermanthi** [comment]
> Try clearing your alarm sound (long press the alarm sound button) or setting it to something else again. If that fixes it then I know what's going wrong

I had not set an alarm sound prior, and it worked once I selected an mp3 for it. Clearing it again produced the same behaviour as before.

**Comment by brandonp2412** [comment]
FYI anyone using the Play store - google takes at least a week to approve any of my changes
