### ISSUE TITLE
Minor imperfections and enhancements

### ISSUE THREAD

**Issue by hertz0022** [brandonp2412/Flexify#65]
Minor imperfections:
1. When adding a new exercise, the strength/cardio text of the option doesn't change, only the icon and the unit (don't understand its presence though - there and in all the other pages when setting a set/ex too - since the unit can be set in the settings. Also, if I change the unit and then the type, the unit doesn't change anymore).
2. I don't understand the body weight option when adding a gym set. I thought it was for body weighed exercises but it takes into account only the weight option in history/graphs, so have to set it manually. Would be nice to have the option as in the plans page.

Enhancements:
1. Muscle categories for exercises. Handy to filter them later.
2. Support for isometric exercises, in addition to strength/cardio.
3. Insights page (for data lovers lol). In addition to the most active days/hours, as Massive already have, maybe some data to check the progresses by exercise, e.g. from the best to the worst. Or some performance trackers by muscle group.
4. The possibility of adding notes to each workout/reps group.
5. The possibility of adding a description or even an image when adding a new exercise. Useful to remember the right execution or just for completeness.
6. More options to set manually the timer (seconds too) and the possibility to pause it.
7. A stopwatch (useful for isometric exercises), maybe directly in the timer page?

Maybe I exaggerated? lol
I have already appreciated a lot your previous project Massive, and this one is even more refined. Thanks a lot, keep it up!

**Comment by brandonp2412** [comment]
2. Body weight is what your body weight was at the time of entering the set. It's used for tracking relative strength over time. E.g. your bench may go from 90 to 100 but if you suddenly weigh 30kg more it's not that impressive

**Comment by brandonp2412** [comment]
I'm going to close this and then create separate issues for the things I will add. I probably won't add too much to the Timer page, since I don't want to make this app a full implementation of an alarm clock.
