### ISSUE TITLE
Calorie burn calculator

### ISSUE THREAD

**Issue by brandonp2412** [brandonp2412/Flexify#72]
Treadmill machines and probably others have a calorie calculator. We could let the user just input this themselves but I can probably find a formula which is close enough to what they use. Since I doubt theirs is highly accurate we can surely find a better formula to use and save the user the time of typing it in.

I'm also skeptical whether these treadmill machines actually account for things like body weight & incline so if we do that then ours will definitely be more accurate.

**Comment by maliksenpai** [comment]
Hello my friend @brandonp2412. I think this applications or machines use formula something like this:

Cal = MET x Weight of Person (kg) x Hours

If it's is okay I will work on it.

**Comment by brandonp2412** [comment]
Feel free my brother I made all these tickets just to be more public with what I'm working on. Pull requests are always welcome.

**Comment by brandonp2412** [comment]
If you can find something that includes Incline that would be great.
