### ISSUE TITLE
Timer progress can prevent the visualization of a exercise's sets

### ISSUE THREAD

**Issue by 64ArthurAraujo** [brandonp2412/Flexify#77]
If there is a lot of exercises in a plan, the last exercise's sets can be a little hard to track due to it being rendered under the timer progress bar

https://github.com/user-attachments/assets/7410f912-3ce6-4ea0-b59b-a67d6c655d8f

**Comment by brandonp2412** [comment]
This also applies to the floating action button obscuring items in all of our lists. I'm going to make all our scrollable lists have a extra bit of wiggle room to pull down further so you can see it above fabs, as well as the bottom progress bar.

FYI timers can be visually hidden from the app (if you like me just want to control it from the notifications area)

Settings -> Timers
![Screenshot_20240717-104738_Flexify](https://github.com/user-attachments/assets/b720689a-ea4c-4208-a6ee-82f897363669)
