### ISSUE TITLE
Individual number of sets per exercise

### ISSUE THREAD

**Issue by Nepochal** [brandonp2412/Flexify#78]
It is possible to overwrite the global rest times per exercise. Could you please also add overwriting the global number of sets?

**Comment by brandonp2412** [comment]
Settings > Timers > Minutes & seconds
Settings > Workouts > Sets per exercise

**Comment by Nepochal** [comment]
That are the global values. But it is not possible to overwrite the number of sets for individual exercises. Or have I overlooked something?

**Comment by Nepochal** [comment]
Sorry, now I found it. I can change it while editing the plan. Sorry and Thank you for your response.
