### ISSUE TITLE
Feature Request: Migration from Massive

### ISSUE THREAD

**Issue by collinarnett** [brandonp2412/Flexify#8]
Hey thanks for all the work you've done on Massive. I've been using it for a long time so I have quite a bit of data in there (especially all the custom workouts). It would be great if I could somehow migrate over to Flexify.

**Comment by brandonp2412** [comment]
Hey so basically you can just import the CSVs for plans & gym sets:
![image](https://github.com/brandonp2412/Flexify/assets/14083541/e8a40363-1a5e-4c1f-87e5-15cd5a1014fc)
![image](https://github.com/brandonp2412/Flexify/assets/14083541/cb3d41c6-6ddc-4275-840d-c1f70b5e4281)

This will generally work however the names of your existing workouts may not map to the static list we provide here on the app. If you want them to be the same you can edit exercise names from the graphs page:
![Screenshot_1711157019](https://github.com/brandonp2412/Flexify/assets/14083541/6df41624-49cf-42a4-8f6f-998f9e5e3406)
![Screenshot_1711157037](https://github.com/brandonp2412/Flexify/assets/14083541/96c08e0a-39d8-4c65-bb0f-a049410aabd7)

**Comment by brandonp2412** [comment]
I just realized we don't have CSV export for plans on Massive. I'll add that shortly. Right now there is only gym set exporting from Massive.

**Comment by brandonp2412** [comment]
As of version 2.33 I've added the ability to export plans (on Massive) and importing on flexify is working: https://gitea.presley.nz/brandon.presley/Massive/commit/d0e76f574b4c3ef8e3ca0d8431304e9c42653733

<img src="https://github.com/brandonp2412/Flexify/assets/14083541/90ffe386-025a-4128-ac72-c930cd3e4fab" height="800"/>

**Comment by brandonp2412** [comment]
Before importing gym sets you may want to delete the defaults provided on first install
![image](https://github.com/brandonp2412/Flexify/assets/14083541/c449453b-6ad1-4808-b98d-92644a419e3d)

Otherwise you may end up with several exercises of similar names.

**Comment by brandonp2412** [comment]
![image](https://github.com/brandonp2412/Flexify/assets/14083541/4e1ad6de-6476-43d0-b999-19a26169dda6)

Import/export logic was moved to the Settings page
