### ISSUE TITLE
Consistent toggle/switch settings

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [brandonp2412/Flexify#80]
In settings, there are options which we can toggle between false and true, thanks to a switch component.

However, for some of them, "false" means "show", when it means "hide" for the others:

![Screenshot_20240720_091834.jpg](https://github.com/user-attachments/assets/50ce3bb0-8b54-4250-aedb-d7e6474dd61c)

I'm suggesting to update them so that they all follow the same logic.
My thinking is that it's harder to process as a user if it's not consistent.

**Comment by brandonp2412** [comment]
Yep good idea. I ended up with a lot of inconsistency when I was still learning how to do these migrations consistently but changes like this should be easy now.
