### ISSUE TITLE
Can't see how many sets should be done until one is entered + proposed change

### ISSUE THREAD

**Issue by dqnne** [brandonp2412/Flexify#81]
Currently you can't see how many sets of an exercise should be done in a plan until at least one is entered and you see the progress bar progress (unless the Ratio trailing option is used). It's mildly annoying to have to either enter a set and then undo it or go into the plan settings if you just want to see what the set amount of an exercise is.

I've started working on a custom indicator to replace the current progress bar that would solve this by having one visible segment for each set. Wanted to check with you if you think something like that could be a good idea at all before opening a PR

**Comment by brandonp2412** [comment]
Go for it my brother. Any PR is welcome the only thing I would reject outright is any inclusion of nonfree libraries/binaries
