### ISSUE TITLE
Feature request: Add options to disable grouping in graphs

### ISSUE THREAD

**Issue by VibrantTreeStump** [brandonp2412/Flexify#82]
I don't really understand how the grouping in graphs works, tbh. So when I look at a graph I don't really know what exactly it is telling me anymore. Maybe that's just me, but I would much rather not group the data in any way and just see all points from all my training sessions. Would be super happy if this were possible.

Side note: The new app is already amazing. I've used Massive for a few months and already liked that, but Flexify is just so snappy and so featureful compared to Massive, I really like it :)

**Comment by brandonp2412** [comment]
That's what history is for

**Comment by VibrantTreeStump** [comment]
What do you mean? There is no graph in the history tab

**Comment by brandonp2412** [comment]
History is listing the exercises as they come, the graphs page has metrics per exercise so they are grouped by nature.
