### ISSUE TITLE
app crashes on launch

### ISSUE THREAD

**Issue by a-damle** [brandonp2412/Flexify#87]
The app has been crashing on launch since I updated from 1.1.59 to 1.1.65. I have attached a log from 1.1.70.
[log.txt](https://github.com/user-attachments/files/16371431/log.txt)

**Comment by brandonp2412** [comment]
Can't replicate this but

**Comment by brandonp2412** [comment]
Also thanks for making this ticket so quickly

**Comment by a-damle** [comment]
1.1.71 fixed the issue for me. Thanks

**Comment by e-zk** [comment]
Damn... Just updated to 1.1.65 before seeing this. Now I have to wait for the damn unnecessarily long F-Droid build cycle.

Regardless, I'm liking the app.
