### ISSUE TITLE
Automated screenshots

### ISSUE THREAD

**Issue by brandonp2412** [brandonp2412/Flexify#9]
We should have a way to generate screenshots and place them in the metadata folder whenever a new release is made.

**Comment by josephnglynn** [comment]
I've had a start at implementing automatic screenshots over [here](https://github.com/josephnglynn/Flexify/tree/automate_screenshots). 
Its still WIP, and shouldn't be run on a real device as you would lose all your data.

Is needing to have 3 separate emulators set up with the size matching the screenshot device size ( phoneScreenshots  / sevenInchScreenshots / tenInchScreenshots ) an acceptable solution? 

It would all be automated when running the script, but before running for the first time you would have to setup named emulators.

Though I'm sure there probably is a way to create emulators from a script.

**Comment by brandonp2412** [comment]
So cool thanks King. Will merge this soon
