### ISSUE TITLE
[bug] Crash on launch, version 1.1.65

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [brandonp2412/Flexify#91]
I have just upgraded to 1.1.65 and the app crashes as soon as I click on the app shortcut :( Even after reboot

I know this isn't the latest version, so I don't know if that gets resolved in the newer versions. I wanted to mention it anyway just in case 😄

Galaxy S20 FE 5G
Android 13
One UI 5.1

**Comment by dqnne** [comment]
It was resolved in 1.1.71 #87
