### ISSUE TITLE
Fails to open

### ISSUE THREAD

**Issue by TechnologyClassroom** [brandonp2412/Flexify#95]
**Describe the bug**
When I try to open the app, it fails to open. Trying to see if it is just me.

Debug log says `android.database.sqlite.SQLiteException: no such column: backup_path (code 1 SQLITE_ERROR): , while compiling: SELECT backup_path, automatic_backups FROM settings`

I do not have backups or cloud anything set.

**To Reproduce**
1. Go to gym.
2. Tap on flexify app.
3. App appears to crash immediately.
4. Open debug log.

**Expected behavior**
App opens despite not having backups.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: GrapheneOS (Android 14)
 - Version 1.1.65 from F-Droid

**Additional context**
Should I try a previous version?

**Comment by brandonp2412** [comment]
Versions past 1.1.65 are fixed and since f-droid takes my signature from github, you can easily upgrade using the releases page https://github.com/brandonp2412/Flexify/releases/tag/1.1.77

**Comment by TechnologyClassroom** [comment]
Great! That works!
